### ISSUE TITLE
Edges not drawn when nested in subgraph

### ISSUE THREAD

**Issue by lemmy** [idekerlab/dot-app#16]
Both inputs below  render correctly with _dot_ or http://www.webgraphviz.com/. However, Cytospace (3.5.1 with 0.9.4) only shows edges for the second one when the edges are not part of the subgraph (see screenshots below).

```dot
digraph DiskGraph {
  subgraph cluster_graph {
    A [style = filled, label="x = 0"]
    B [label="x = 1"];
    C [label="x = 2"];
    A -> B [label="",color="black",fontcolor="black"];
    B -> C [label="",color="black",fontcolor="black"];
    {rank = same; A;}
    {rank = same; B;}
    {rank = same; C;}
  }
}
```

![inside](https://user-images.githubusercontent.com/88777/44742312-1752ad00-aaef-11e8-8d5c-8f80d2b0c45f.png)

```dot
digraph DiskGraph {
  subgraph cluster_graph {
    A [style = filled, label="x = 0"]
    B [label="x = 1"];
    C [label="x = 2"];
    {rank = same; A;}
    {rank = same; B;}
    {rank = same; C;}
  }
  A -> B [label="",color="black",fontcolor="black"];
  B -> C [label="",color="black",fontcolor="black"];
}
```

![outside](https://user-images.githubusercontent.com/88777/44742313-1752ad00-aaef-11e8-99a1-8e0c35ef2ee7.png)

**Comment by bdtfitts** [comment]
Fixed in 0.9.5
