### ISSUE TITLE
Tooltips not translated

### ISSUE THREAD

**Issue by georgefst** [idekerlab/dot-app#18]
Tooltip information does not seem to be making its way through to Cytoscape for any graph that I have tried.

I have constructed a trivial graph:

`
digraph g {
	foo	 [tooltip=bar];
}
`

I would expect a bypass in the 'Tooltip' row in Cytoscape for the node `foo`, but there is no evidence of the tooltip information having been picked up.

**Comment by bdtfitts** [comment]
Hi there
Thanks for taking the time to reach out about this. The logic for tooltips have been added (quite unfortunate that it was missed for this long)

**Comment by georgefst** [comment]
Thanks. I'd totally forgotten about this, but it will certainly be useful.

**Comment by bdtfitts** [comment]
The release with the requested feature is now live in the App Store so you should be able to get it now.
